// Generated by ReScript, PLEASE EDIT WITH CARE

import * as ORSet from "./crdt/ORSet.mjs";
import * as Channel from "./transport/Channel.mjs";
import * as Js_math from "@rescript/runtime/lib/es6/Js_math.js";
import * as GCounter from "./crdt/GCounter.mjs";
import * as PNCounter from "./crdt/PNCounter.mjs";
import * as Capabilities from "./adapters/Capabilities.mjs";

let CRDT = {
  GCounter: undefined,
  PNCounter: undefined,
  ORSet: undefined,
  LWWRegister: undefined
};

let Adapters = {
  Capabilities: undefined
};

let Transport = {
  Channel: undefined
};

function generateNodeId() {
  let timestamp = Date.now() | 0;
  let random = Js_math.random_int(0, 999999);
  return `node_` + String(timestamp) + `_` + String(random);
}

function init(serverUrl) {
  let nodeId = generateNodeId();
  let capabilities = Capabilities.probe();
  console.log("=== Laniakea Client ===");
  console.log("Node ID:", nodeId);
  Capabilities.log(capabilities);
  let config = {
    url: serverUrl,
    nodeId: nodeId,
    capabilities: capabilities
  };
  let connection = Channel.make(config);
  Channel.connect(connection, serverUrl + "/socket");
  return {
    nodeId: nodeId,
    capabilities: capabilities,
    connection: connection
  };
}

let state = {
  counter: GCounter.make(),
  client: undefined
};

function start(serverUrl) {
  let client = init(serverUrl);
  state.client = client;
  Channel.joinCrdt(client.connection, "demo:counter", response => {
    console.log("Initial state:", response);
  }, response => {
    console.log("State updated:", response);
  });
}

function increment() {
  let client = state.client;
  if (client !== undefined) {
    state.counter = GCounter.increment(state.counter, client.nodeId);
    console.log("Local value:", GCounter.value(state.counter));
    return Channel.increment(client.connection);
  } else {
    console.error("Not initialized");
    return;
  }
}

function getValue() {
  return GCounter.value(state.counter);
}

let CounterDemo = {
  state: state,
  start: start,
  increment: increment,
  getValue: getValue
};

console.log("Laniakea Client loaded");

console.log("Use Laniakea.init(~serverUrl) to connect");

let probeCapabilities = Capabilities.probe;

let makeGCounter = GCounter.make;

let makePNCounter = PNCounter.make;

let makeORSet = ORSet.make;

export {
  CRDT,
  Adapters,
  Transport,
  probeCapabilities,
  makeGCounter,
  makePNCounter,
  makeORSet,
  generateNodeId,
  init,
  CounterDemo,
}
/* state Not a pure module */
