// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Option from "@rescript/runtime/lib/es6/Belt_Option.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";
import * as Js_null_undefined from "@rescript/runtime/lib/es6/Js_null_undefined.js";

function make() {
  return {
    value: undefined,
    timestamp: 0,
    nodeId: undefined,
    version: 0
  };
}

function makeWith(value, nodeId) {
  return {
    value: Primitive_option.some(value),
    timestamp: Date.now() | 0,
    nodeId: nodeId,
    version: 1
  };
}

function set(reg, value, nodeId) {
  return {
    value: Primitive_option.some(value),
    timestamp: Date.now() | 0,
    nodeId: nodeId,
    version: reg.version + 1 | 0
  };
}

function setWithTimestamp(reg, value, nodeId, timestamp) {
  return {
    value: Primitive_option.some(value),
    timestamp: timestamp,
    nodeId: nodeId,
    version: reg.version + 1 | 0
  };
}

function value(reg) {
  return reg.value;
}

function timestamp(reg) {
  return reg.timestamp;
}

function nodeId(reg) {
  return reg.nodeId;
}

function merge(a, b) {
  let winner;
  if (a.timestamp > b.timestamp) {
    winner = a;
  } else if (b.timestamp > a.timestamp) {
    winner = b;
  } else {
    let aNode = Belt_Option.getWithDefault(a.nodeId, "");
    let bNode = Belt_Option.getWithDefault(b.nodeId, "");
    winner = aNode >= bNode ? a : b;
  }
  return {
    value: winner.value,
    timestamp: winner.timestamp,
    nodeId: winner.nodeId,
    version: Math.max(a.version, b.version) + 1 | 0
  };
}

function toWire(reg) {
  return {
    type: "lww_register",
    value: Js_null_undefined.fromOption(reg.value),
    timestamp: reg.timestamp,
    node_id: Js_null_undefined.fromOption(reg.nodeId),
    version: reg.version
  };
}

function fromWire(wire) {
  return {
    value: Primitive_option.fromNullable(wire.value),
    timestamp: wire.timestamp,
    nodeId: Primitive_option.fromNullable(wire.node_id),
    version: wire.version
  };
}

export {
  make,
  makeWith,
  set,
  setWithTimestamp,
  value,
  timestamp,
  nodeId,
  merge,
  toWire,
  fromWire,
}
/* No side effect */
