// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Option from "@rescript/runtime/lib/es6/Belt_Option.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

globalThis.__laniakea = globalThis.__laniakea || {};
  globalThis.__laniakea.hasWorkerSupport = typeof Worker !== 'undefined';
  globalThis.__laniakea.hasSABSupport = typeof SharedArrayBuffer !== 'undefined';
  globalThis.__laniakea.hasWebTransportSupport = typeof WebTransport !== 'undefined';
;

function parseConnectionType(raw) {
  if (raw === undefined) {
    return "Unknown";
  }
  switch (raw) {
    case "cellular" :
      return "Cellular";
    case "ethernet" :
      return "Ethernet";
    case "wifi" :
      return "Wifi";
    default:
      return "Unknown";
  }
}

function parseEffectiveType(raw) {
  if (raw === undefined) {
    return "G4";
  }
  switch (raw) {
    case "2g" :
      return "G2";
    case "3g" :
      return "G3";
    case "slow-2g" :
      return "Slow2g";
    default:
      return "G4";
  }
}

function probe() {
  let memory = Belt_Option.mapWithDefault(Primitive_option.fromNullable(navigator.deviceMemory), 2048, mem => mem * 1024.0 | 0);
  return {
    hasWorkers: globalThis.__laniakea.hasWorkerSupport,
    hasSharedArrayBuffer: globalThis.__laniakea.hasSABSupport,
    hasWebTransport: globalThis.__laniakea.hasWebTransportSupport,
    memoryMb: memory,
    connectionType: parseConnectionType(Primitive_option.fromNullable(navigator.connection.type)),
    effectiveType: parseEffectiveType(Primitive_option.fromNullable(navigator.connection.effectiveType))
  };
}

function connectionTypeToString(ct) {
  switch (ct) {
    case "Wifi" :
      return "wifi";
    case "Ethernet" :
      return "ethernet";
    case "Cellular" :
      return "cellular";
    case "Unknown" :
      return "unknown";
  }
}

function effectiveTypeToString(et) {
  switch (et) {
    case "Slow2g" :
      return "slow-2g";
    case "G2" :
      return "2g";
    case "G3" :
      return "3g";
    case "G4" :
      return "4g";
  }
}

function toWire(caps) {
  return {
    hasWorkers: caps.hasWorkers,
    hasSharedArrayBuffer: caps.hasSharedArrayBuffer,
    hasWebTransport: caps.hasWebTransport,
    memoryMb: caps.memoryMb,
    connectionType: connectionTypeToString(caps.connectionType),
    effectiveType: effectiveTypeToString(caps.effectiveType)
  };
}

function log(caps) {
  console.log("Capabilities:", toWire(caps));
}

export {
  parseConnectionType,
  parseEffectiveType,
  probe,
  connectionTypeToString,
  effectiveTypeToString,
  toWire,
  log,
}
/*  Not a pure module */
