// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Phoenix from "phoenix";
import * as Capabilities from "../adapters/Capabilities.mjs";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

let Phoenix$1 = {};

function make(config) {
  return {
    socket: undefined,
    channel: undefined,
    state: "Disconnected",
    nodeId: config.nodeId,
    capabilities: config.capabilities
  };
}

function connect(conn, url) {
  conn.state = "Connecting";
  let params = {
    node_id: conn.nodeId,
    capabilities: Capabilities.toWire(conn.capabilities)
  };
  let socket = new Phoenix.Socket(url, {
    params: params
  });
  socket.connect();
  conn.socket = Primitive_option.some(socket);
  conn.state = "Connected";
}

function joinCrdt(conn, key, onState, onUpdate) {
  let socket = conn.socket;
  if (socket !== undefined) {
    let topic = "crdt:" + key;
    let channel = Primitive_option.valFromOption(socket).channel(topic, {});
    channel.join().receive("ok", response => {
      console.log("Joined", topic);
      onState(response);
    }).receive("error", err => {
      console.error("Failed to join", err);
    });
    channel.on("state_updated", payload => onUpdate(payload));
    conn.channel = Primitive_option.some(channel);
    return;
  }
  console.error("Cannot join channel: not connected");
}

function increment(conn) {
  let channel = conn.channel;
  if (channel !== undefined) {
    Primitive_option.valFromOption(channel).push("increment", {}).receive("ok", param => {}).receive("error", err => {
      console.error("Increment failed", err);
    });
  } else {
    console.error("No channel");
  }
}

function incrementBy(conn, amount) {
  let channel = conn.channel;
  if (channel !== undefined) {
    Primitive_option.valFromOption(channel).push("increment_by", {
      amount: amount
    }).receive("ok", param => {}).receive("error", err => {
      console.error("Increment failed", err);
    });
  } else {
    console.error("No channel");
  }
}

function decrement(conn) {
  let channel = conn.channel;
  if (channel !== undefined) {
    Primitive_option.valFromOption(channel).push("decrement", {}).receive("ok", param => {}).receive("error", err => {
      console.error("Decrement failed", err);
    });
  } else {
    console.error("No channel");
  }
}

function merge(conn, state) {
  let channel = conn.channel;
  if (channel !== undefined) {
    Primitive_option.valFromOption(channel).push("merge", {
      state: state
    }).receive("ok", param => {
      console.log("Merge successful");
    }).receive("error", err => {
      console.error("Merge failed", err);
    });
  } else {
    console.error("No channel");
  }
}

function sync(conn, callback) {
  let channel = conn.channel;
  if (channel !== undefined) {
    Primitive_option.valFromOption(channel).push("sync", {}).receive("ok", response => callback(response)).receive("error", err => {
      console.error("Sync failed", err);
    });
  } else {
    console.error("No channel");
  }
}

function leave(conn) {
  let channel = conn.channel;
  if (channel !== undefined) {
    Primitive_option.valFromOption(channel).leave();
    conn.channel = undefined;
    return;
  }
}

function disconnect(conn) {
  leave(conn);
  let socket = conn.socket;
  if (socket !== undefined) {
    Primitive_option.valFromOption(socket).disconnect();
    conn.socket = undefined;
    conn.state = "Disconnected";
    return;
  }
}

function getState(conn) {
  return conn.state;
}

export {
  Phoenix$1 as Phoenix,
  make,
  connect,
  joinCrdt,
  increment,
  incrementBy,
  decrement,
  merge,
  sync,
  leave,
  disconnect,
  getState,
}
/* phoenix Not a pure module */
